<link rel="stylesheet" href="../../js/easyui-theme/easyui/themes/gray/easyui.css">
<link rel="stylesheet" href="../../js/jquery-easyui-1.4.1/themes/icon.css">
<link rel="stylesheet" href="../../css/movie.css">
<link rel="stylesheet" href="../../css/manager.css">
<link rel="stylesheet" href="../../css/movie-detail.css">
<script type="text/javascript" src="../../js/common/common.js"></script>
<script type="text/javascript" src="../../js/jquery-easyui-1.4.1/jquery.min.js"></script>
<script type="text/javascript" src="../../js/jquery-easyui-1.4.1/jquery.easyui.min.js"></script>
<script type="text/javascript" src="../../js/jquery-easyui-1.4.1/locale/easyui-lang-zh_CN.js"></script>